spring:
  application:
    name: invoice-request-processor
  jms:
    servicebus:
      connection-string: Endpoint=sb://inter-service-connector.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=FCJ7ggLjuzsj9p35Om9miQiJL5n/sfjQV+ASbKlGGqY=
      pricing-tier: basic

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml
  default-schema: az_function

